# Generated by Django 4.2.1 on 2023-05-29 15:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'causes',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('practitioner', 'Practitioner'), ('patient', 'Patient')], max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'diets',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, null=True)),
                ('name_persian', models.CharField(max_length=255, unique=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('icode', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDrugLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('drug_dose', models.CharField(max_length=255, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_drug_link',
            },
        ),
        migrations.CreateModel(
            name='DiseasePharmacoTherapyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_pharmaco_therapy_link',
            },
        ),
        migrations.CreateModel(
            name='DiseasePreventionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_prevention_link',
            },
        ),
        migrations.CreateModel(
            name='DiseaseRegimentalTherapyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_regimental_therapy_link',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_symptom_link',
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatmentPrincipleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_treatment_principle_link',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diseases', models.ManyToManyField(through='backend.DiseaseDrugLink', to='backend.disease')),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='DrugPharmacoTherapyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.drug')),
            ],
            options={
                'db_table': 'drug_pharmaco_therapy_link',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PractionerPatientLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
            options={
                'db_table': 'practitioner_patient_link',
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'practitioner',
            },
        ),
        migrations.CreateModel(
            name='RegimentalTherapy',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diseases', models.ManyToManyField(through='backend.DiseaseRegimentalTherapyLink', to='backend.disease')),
            ],
            options={
                'db_table': 'regimental_therapies',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('icode', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diseases', models.ManyToManyField(through='backend.DiseaseSymptomLink', to='backend.disease')),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPrinciple',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diseases', models.ManyToManyField(through='backend.DiseaseTreatmentPrincipleLink', to='backend.disease')),
            ],
            options={
                'db_table': 'treatment_principles',
            },
        ),
        migrations.CreateModel(
            name='SymptomRegimentalTherapyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('regimental_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.regimentaltherapy')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.symptom')),
            ],
            options={
                'db_table': 'symptom_regimental_therapy_link',
            },
        ),
        migrations.AddField(
            model_name='symptom',
            name='regimental_therapies',
            field=models.ManyToManyField(through='backend.SymptomRegimentalTherapyLink', to='backend.regimentaltherapy'),
        ),
        migrations.AddField(
            model_name='regimentaltherapy',
            name='symptoms',
            field=models.ManyToManyField(through='backend.SymptomRegimentalTherapyLink', to='backend.symptom'),
        ),
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diseases', models.ManyToManyField(through='backend.DiseasePreventionLink', to='backend.disease')),
            ],
            options={
                'db_table': 'preventions',
            },
        ),
        migrations.CreateModel(
            name='PractitionerDiseaseLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
                ('practitioner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.practitioner')),
            ],
            options={
                'db_table': 'practitioner_disease_link',
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='diseases',
            field=models.ManyToManyField(through='backend.PractitionerDiseaseLink', to='backend.disease'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='patients',
            field=models.ManyToManyField(through='backend.PractionerPatientLink', to='backend.patient'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practionerpatientlink',
            name='practitioner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.practitioner'),
        ),
        migrations.CreateModel(
            name='PharmacoTherapy',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=255, null=True)),
                ('name_persian', models.CharField(max_length=255, null=True)),
                ('name_urdu', models.CharField(max_length=255, null=True)),
                ('name_urdu_roman', models.CharField(max_length=255, null=True)),
                ('name_arabic', models.CharField(max_length=255, null=True)),
                ('name_hindi', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('diseases', models.ManyToManyField(through='backend.DiseasePharmacoTherapyLink', to='backend.disease')),
                ('drugs', models.ManyToManyField(through='backend.DrugPharmacoTherapyLink', to='backend.drug')),
            ],
            options={
                'db_table': 'pharmaco_therapies',
            },
        ),
        migrations.CreateModel(
            name='PatientSymptomLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
                ('symptom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.symptom')),
            ],
            options={
                'db_table': 'patient_symptom_link',
            },
        ),
        migrations.CreateModel(
            name='PatientDiseaseLink',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
            options={
                'db_table': 'patient_disease_link',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(through='backend.PatientDiseaseLink', to='backend.disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='practitioners',
            field=models.ManyToManyField(through='backend.PractionerPatientLink', to='backend.practitioner'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(through='backend.PatientSymptomLink', to='backend.symptom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugpharmacotherapylink',
            name='pharmaco_therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pharmacotherapy'),
        ),
        migrations.AddField(
            model_name='drug',
            name='pharmaco_therapies',
            field=models.ManyToManyField(through='backend.DrugPharmacoTherapyLink', to='backend.pharmacotherapy'),
        ),
        migrations.AddField(
            model_name='diseasetreatmentprinciplelink',
            name='treatment_principle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.treatmentprinciple'),
        ),
        migrations.AddField(
            model_name='diseasesymptomlink',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.symptom'),
        ),
        migrations.AddField(
            model_name='diseaseregimentaltherapylink',
            name='regimental_therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.regimentaltherapy'),
        ),
        migrations.AddField(
            model_name='diseasepreventionlink',
            name='prevention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.prevention'),
        ),
        migrations.AddField(
            model_name='diseasepharmacotherapylink',
            name='pharmaco_therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pharmacotherapy'),
        ),
        migrations.AddField(
            model_name='diseasedruglink',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.drug'),
        ),
        migrations.CreateModel(
            name='DiseaseDietLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('diet_type', models.CharField(max_length=255)),
                ('diet_dose', models.CharField(max_length=255, null=True)),
                ('diet_usage_time', models.CharField(max_length=255, null=True)),
                ('diet_usage_with', models.CharField(max_length=255, null=True)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.diet')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_diet_link',
            },
        ),
        migrations.CreateModel(
            name='DiseaseCauseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cause')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
            options={
                'db_table': 'disease_cause_link',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.ManyToManyField(through='backend.DiseaseCauseLink', to='backend.cause'),
        ),
        migrations.AddField(
            model_name='disease',
            name='diets',
            field=models.ManyToManyField(through='backend.DiseaseDietLink', to='backend.diet'),
        ),
        migrations.AddField(
            model_name='disease',
            name='drugs',
            field=models.ManyToManyField(through='backend.DiseaseDrugLink', to='backend.drug'),
        ),
        migrations.AddField(
            model_name='disease',
            name='pharmaco_therapies',
            field=models.ManyToManyField(through='backend.DiseasePharmacoTherapyLink', to='backend.pharmacotherapy'),
        ),
        migrations.AddField(
            model_name='disease',
            name='preventions',
            field=models.ManyToManyField(through='backend.DiseasePreventionLink', to='backend.prevention'),
        ),
        migrations.AddField(
            model_name='disease',
            name='regimental_therapies',
            field=models.ManyToManyField(through='backend.DiseaseRegimentalTherapyLink', to='backend.regimentaltherapy'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(through='backend.DiseaseSymptomLink', to='backend.symptom'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_principles',
            field=models.ManyToManyField(through='backend.DiseaseTreatmentPrincipleLink', to='backend.treatmentprinciple'),
        ),
        migrations.AddField(
            model_name='diet',
            name='diseases',
            field=models.ManyToManyField(through='backend.DiseaseDietLink', to='backend.disease'),
        ),
        migrations.AddField(
            model_name='cause',
            name='diseases',
            field=models.ManyToManyField(through='backend.DiseaseCauseLink', to='backend.disease'),
        ),
    ]
